Metrics/LineLength:
  Max: 200
AllCops:
  Exclude:
    - bin/*
    - node_modules/**/*
    - db/**/*
Style/Documentation:
  Enabled:
    false
Style/ClassAndModuleChildren:
  Enabled:
    false
Naming/UncommunicativeMethodParamName:
  Enabled:
    false
Metrics/BlockLength:
  Exclude:
    - config/initializers/**
    - config/environments/**
    - config/routes.rb
    - lib/tasks/**
    - spec/**/*.rb