inherit_from:
  - .rubocop_airbnb.yml
Metrics/LineLength:
  Max: 200
AllCops:
  Exclude:
    - bin/*
    - node_modules/**/*
    - db/**/*
Airbnb/OptArgParameters:
  Enabled:
    false
Airbnb/DefaultScope:
  Enabled:
    false