default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 'localhost'

development:
  <<: *default
  database: starter-postgres-rails-react-dev

test:
  <<: *default
  database: starter-postgres-rails-react-test

production:
  <<: *default
  database: starter-postgres-rails-react